accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="/accounts/login/")),
    path("accounts/", include("accounts.urls")),
    path("demo/", include("demo.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo/urls.py
from django.urls import path

from . import views


app_name = "demo"
urlpatterns = [
    path("upload/", views.upload, name="upload"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    class Meta(object):
        db_table = "user"

    login_count = models.IntegerField(verbose_name="ログイン回数", default=0)

    def post_login(self):

        self.login_count += 1
        self.save()

demo/models.py
from django.db import models


class InputImage(models.Model):
    class Meta(object):
        db_table = "input_image"

    title = models.CharField(verbose_name="title", null=True, blank=True, max_length=255)
    input_image = models.ImageField(
        verbose_name="input_image", null=True, blank=True, upload_to="images/"
    )

    def __str__(self) -> str:
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ObjectDoesNotExist

from .models import User


class RegisterForm(forms.ModelForm):
    """ユーザー登録画面用のフォーム"""

    class Meta:
        # 利用するモデルクラスを指定
        model = User
        # 利用するモデルのフィールドを指定
        fields = (
            "username",
            "email",
            "password",
        )
        # ウィジェットを上書き
        widgets = {
            "username": forms.TextInput(attrs={"placeholder": "username"}),
            "password": forms.PasswordInput(attrs={"placeholder": "password"}),
        }

    password2 = forms.CharField(
        label="確認用パスワード",
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={"placeholder": "確認用パスワード"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # フィールドの属性を書き換え
        self.fields["email"].required = True
        self.fields["email"].widget.attrs = {"placeholder": "メールアドレス"}

    def clean_username(self):
        value = self.cleaned_data["username"]
        if len(value) < 3:
            raise forms.ValidationError("%(min_length)s文字以上で入力してください", params={"min_length": 3})
        return value

    def clean_email(self):
        value = self.cleaned_data["email"]
        return value

    def clean_password(self):
        value = self.cleaned_data["password"]
        return value

    def clean(self):
        password = self.cleaned_data["password"]
        password2 = self.cleaned_data["password2"]
        if password != password2:
            raise forms.ValidationError("パスワードと確認用パスワードが合致しません")
        # ユニーク制約を自動でバリデーションしてほしい場合は super の clean() を明示的に呼び出す
        super().clean()


class LoginForm(forms.Form):
    """ログイン画面用のフォーム"""

    username = UsernameField(
        label="username",
        max_length=255,
        widget=forms.TextInput(attrs={"placeholder": "username", "autofocus": True}),
    )

    password = forms.CharField(
        label="password",
        strip=False,
        widget=forms.PasswordInput(attrs={"placeholder": "password"}, render_value=True),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user_cache = None

    def clean_password(self):
        value = self.cleaned_data["password"]
        return value

    def clean_username(self):
        value = self.cleaned_data["username"]
        if len(value) < 3:
            raise forms.ValidationError("%(min_length)s文字以上で入力してください", params={"min_length": 3})
        return value

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = get_user_model().objects.get(username=username)
        except ObjectDoesNotExist:
            raise forms.ValidationError("正しいユーザー名を入力してください")
        # パスワードはハッシュ化されて保存されているので平文での検索はできない
        if not user.check_password(password):
            raise forms.ValidationError("正しいユーザー名とパスワードを入力してください")
        # 取得したユーザーオブジェクトを使い回せるように内部に保持しておく
        self.user_cache = user

    def get_user(self):
        return self.user_cache


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "last_name",
            "first_name",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs = {"placeholder": "ユーザー名"}
        self.fields["email"].required = True
        self.fields["email"].widget.attrs = {"placeholder": "メールアドレス"}
        # self.fields['password'].widget = forms.PasswordInput(attrs={'placeholder': 'パスワード'}, render_value=True)
        self.fields["last_name"].widget.attrs = {"placeholder": "苗字"}
        self.fields["first_name"].widget.attrs = {"placeholder": "名前"}

    def clean_username(self):
        value = self.cleaned_data["username"]
        return value

    def clean_email(self):
        value = self.cleaned_data["email"]
        return value

demo/forms.py
from django import forms

from .models import InputImage


class InputImageForm(forms.ModelForm):
    class Meta:
        model = InputImage
        fields = ("title", "input_image")

accounts/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View

from .forms import LoginForm, ProfileForm, RegisterForm


logger = logging.getLogger(__name__)


class LoginView(View):
    def get(self, request, *args, **kwargs):
        """GETリクエスト用のメソッド"""
        # すでにログインしている場合はショップ画面へリダイレクト
        if request.user.is_authenticated:
            return redirect(reverse("demo:upload"))

        context = {
            "form": LoginForm(),
        }
        # ログイン画面用のテンプレートに値が空のフォームをレンダリング
        return render(request, "accounts/login.html", context)

    def post(self, request, *args, **kwargs):
        """POSTリクエスト用のメソッド"""
        # リクエストからフォームを作成
        form = LoginForm(request.POST)
        # バリデーション（ユーザーの認証も合わせて実施）
        if not form.is_valid():
            # バリデーションNGの場合はログイン画面のテンプレートを再表示
            return render(request, "accounts/login.html", {"form": form})

        # ユーザーオブジェクトをフォームから取得
        user = form.get_user()

        # ログイン処理（取得したユーザーオブジェクトをセッションに保存 & ユーザーデータを更新）
        auth_login(request, user)

        # ログイン後処理（ログイン回数を増やしたりする。本来は user_logged_in シグナルを使えばもっと簡単に書ける）
        user.post_login()

        # ロギング
        logger.info("User(id={}) has logged in.".format(user.id))

        # フラッシュメッセージを画面に表示
        messages.info(request, "ログインしました。")

        # ショップ画面にリダイレクト
        return redirect(reverse("demo:upload"))


login = LoginView.as_view()

demo/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import View

from .forms import InputImageForm


logger = logging.getLogger(__name__)


class UploadView(LoginRequiredMixin, View):
    def get(self, request, *arts, **kwargs):

        context = {"form": InputImageForm()}
        return render(request, "demo/upload.html", context)

    def post(self, request, *args, **kwargs):

        form = InputImageForm(request.POST, request.FILES)
        input_image = form.save(commit=False)
        input_image.submitter = self.request.user  # モデルオブジェクトの save() 時にファイルがアップロードされる
        input_image.save()
        return redirect(reverse("demo:upload"))


upload = UploadView.as_view()

templates/_message.html
{% block messages %}
{% if messages %}
<div class="ui relaxed divided list">
    {% for message in messages %}
    <div class="ui {% if message.tags %}{{ message.tags }}{% endif %} message">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endblock messages %}

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}Login{% endblock %}

{% block extra_css %}
<style type="text/css">
    .container > .grid {
        height: 100%;
    }

    .column {
        max-width: 400px;
    }

    p.red.message {
        color: #db2828;
        margin: 0.8em 0 0 0.8em;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal image header">
            <img src="{% static 'images/logo.png' %}" class="image">
            <div class="content">Login</div>
        </h2>

        <form action="{% url 'accounts:login' %}" method="post" class="ui form">
            <div class="ui stacked segment">
                {# --- 全体エラーメッセージ --- #}
                {% if form.non_field_errors %}
                <div class="ui red message">
                    <div class="header">Error</div>
                    <ul class="list">
                        {% for non_field_error in form.non_field_errors %}
                        <li>{{ non_field_error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}

                {% for field in form %}
                <div class="field{% if field.errors %} error{% endif %}">
                    {# --- 入力フィールド --- #}
                    <div class="ui input{% if field.errors %} error{% endif %}">
                        {{ field }}
                    </div>
                    {# --- 入力フィールドごとのエラーメッセージ（最初のエラーのみを表示） --- #}
                    {% if field.errors %}
                    <p class="red message">{{ field.errors.0 }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                {% csrf_token %}
                <button type="submit" class="ui fluid teal submit button">Login</button>
            </div>
        </form>

    </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %}{% endblock %}</title>

    {# --- css --- #}
    <link rel="stylesheet" href="{% static 'vendor/semantic/semantic.min.css' %}">
    <style type="text/css">
        body {
            background-color: #dadada;
        }
        body > .container {
            height: 100%;
        }
    </style>
    {% block extra_css %}{% endblock %}
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
<div class="ui container">
    {% include '_message.html' %}
    {% block content %}{% endblock %}
</div>

{% comment %} {# TODO #}
{% if user.is_authenticated %}
<a href="{% url 'accounts:logout' %}">ログアウト</a> | <a href="{% url 'accounts:profile' %}">プロフィール</a> | <a href="{% url 'shop:index' %}">ショップ</a>
{% endif %} {% endcomment %}

{# --- js --- #}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'vendor/semantic/semantic.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

templates/demo/upload.html
{% extends "base.html"%}
{% block title %}Upload{% endblock%}

{% block content%}
<h1>Upload Images</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit" value="投稿">
</form>
{% endblock%}